name: Build & Deploy

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm install && npm test && npm run build

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload artifacts in release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/*

    - name: Configure git
      run: |
        git config user.name "github-actions[bot]"
        git config --local user.email "action@github.com"

    - name: Commit and Push changes to dist branch
      run: |
        git checkout -b dist
        git add dist/main.js
        git commit -m ${{ github.ref }}"-release main.js"
        git push origin dist
